# Generated by Django 3.0.4 on 2020-03-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('describe', models.CharField(max_length=128)),
                ('minutes', models.IntegerField()),
                ('shift_begin', models.TimeField()),
                ('shift_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('npwz', models.CharField(blank=True, max_length=12)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('staff_type', models.IntegerField(choices=[(1, 'pielęgniarka'), (2, 'pomocniczy'), (3, 'lekarz'), (4, 'psycholog'), (5, 'psychoterapeuta')])),
                ('employee_type', models.IntegerField(choices=[(1, 'wewnętrzny'), (2, 'zewnętrzny'), (3, 'kontraktowy')])),
                ('begin_work', models.DateField()),
                ('end_work', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='YearSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('staff', models.ManyToManyField(to='scheduler.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.DateField()),
                ('done_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_id', to='scheduler.Shifts')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_id', to='scheduler.Shifts')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Unit')),
                ('yearschedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.YearSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='PartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_time', models.DecimalField(decimal_places=4, max_digits=5)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='BaseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_time', models.DecimalField(decimal_places=0, max_digits=3)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staff')),
            ],
        ),
    ]
